name: ShrinkWrap vs Slivers

# Accepts 'flutter' or 'dart'
type: flutter

# Configuration for each step
steps:
  - name: List of lists with ShrinkWrap
    directory: step_01
    has_solution: true
  - name: List of lists with Slivers
    directory: step_02
    has_solution: false
